version: '3'
services:

  todotests:
      image: todotests:latest
      depends_on:
        - todofront
        - todoback
      environment:
        - FRONT_HOST=todofront
      restart: on-failure

  todofront:
    image: todofrontend:latest
    depends_on:
      - todoback
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_HOST=todoback
    restart: on-failure
    
  todoback:
    image: todobackend:latest
    ports:
      - "3001:3001"
    restart: on-failure